name: notepad-plus-plus
adopt-info: notepad-plus-plus
summary: notepad-plus-plus is a free source code editor.
description: |
 Based on the powerful editing component Scintilla, notepad-plus-plus is written in C++ and uses pure Win32 API and STL which ensures a higher execution speed and smaller program size. By optimizing as many routines as possible without losing user friendliness, notepad-plus-plus is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  notepad-plus-plus:
    command: notepad-plus-plus
    desktop: usr/share/applications/notepad-plus-plus.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media, icon-themes, wine-runtime, wine-5-stable ]

parts:
  notepad-plus-plus:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n1)
      snapcraftctl set-version "$ver"
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - winedata
    build-packages: [wget]
