name: notepad-plus-plus
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: notepad-plus-plus is a free source code editor.
description: |
 Based on the powerful editing component Scintilla, notepad-plus-plus is written in C++ and uses pure Win32 API and STL which ensures a higher execution speed and smaller program size. By optimizing as many routines as possible without losing user friendliness, notepad-plus-plus is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform

apps:
  notepad-plus-plus:
    command: notepad-plus-plus
    desktop: usr/share/applications/notepad-plus-plus.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media, wine-platform-plug ]

parts:
  notepad-plus-plus:
    plugin: nil
    source: ./src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://notepad-plus-plus.org/download -q -S -O - 2>&1 | grep 'Version</t' | cut -c19-24 | sed 's| -||' | sed 's/ //g')
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [wget, p7zip-full]
